name: 'Close Stale Issues & PRs'
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v4.1.1
        with:
          # stale issue labels
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'work-in-progress'
          # stale pr lables
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'work-in-progress'
          # issue close & warning days
          days-before-issue-stale: 15
          days-before-issue-close: 2
          # pr close & warning days
          days-before-pr-stale: 15
          days-before-pr-close: 2
          # stale issue messages
          stale-issue-message: >
           This issue has been open for a few days with no activity. It will be closed soon if no further activity occurs.
          close-issue-message: >
           This issue has been closed because it has not received any activity in the last few days
          # pr issue messages
          stale-pr-message: 'This PR has been open few days with no activity. It will be closed soon if no further activity occurs'
          close-pr-message: 'This PR has been closed because it has not received any activity in the last few days'
